export const defaultValues = {
  birthDate: "",
  bloodDate: "",
  city: "",
  country: "",
  crio: "",
  dateCrio: "",
  doctorConsultation: "",
  doctorConsultationDate: "",
  fatherName: "",
  firstName: "",
  gender: "",
  geneticistConsultation: "",
  geneticistConsultationDate: "",
  lastName: "",
  mutation: "",
  recommendations: "",
  region: "",
  seek: "",
  stage: "",
};
