import type { Metadata } from "next";
import "../globals.css";

import { Header } from "@/widgets";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      {children}
      <Toaster position="top-center" />
    </div>
  );
}
